title: Sure-Step Development Documentation
baseurl: ""
url: ""
markdown: kramdown
theme: minima
plugins: []

# Build settings
exclude:
  - node_modules
  - vendor

# kramdown options
kramdown:
  input: GFM
